name: doclink
description: Introducing our user-friendly app that simplifies the process of booking a doctor's appointment. With just a few clicks, you can easily schedule an appointment with a doctor of your choice based on specialty or proximity.  Our app also enables you to communicate with your doctor through in-app chat or video/phone calls. You can receive medical attention from the comfort of your home, eliminating the need to travel and wait in long queues.  The app also includes an in-app map function that enables you to find the nearest doctor based on your location. You can easily search for a doctor based on their specialty and get quick access to their services.  Overall, our app simplifies the process of booking and attending a doctor's appointment. Download our app today and take the first step towards easy access to quality medical care.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.0
  flutter_hooks: ^0.18.6
  riverpod: ^2.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18
  lottie: ^2.2.0
  firebase_dynamic_links: ^5.0.16
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.4.1
  firebase_storage: ^11.0.15
  firebase_messaging: ^14.2.6
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  image_picker: ^0.8.7
  path: ^1.8.2
  path_provider: ^2.0.13
  icons_plus: ^4.0.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
  dio: ^5.1.0
  image: ^4.0.15
  salomon_bottom_bar: ^3.3.1
  uuid: ^3.0.7
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/specialties/
