// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvrW1fUM6m5YkggP74z3HZR4DH7Zci0zg',
    appId: '1:801641693646:web:24cc56f25cebf1df316b9f',
    messagingSenderId: '801641693646',
    projectId: 'doclink-d30a3',
    authDomain: 'doclink-d30a3.firebaseapp.com',
    storageBucket: 'doclink-d30a3.appspot.com',
    measurementId: 'G-BGEVXFPELP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlYTy_mNkiAC7piV2tysyJssC2kraY2c',
    appId: '1:801641693646:android:d927c02050c8a2cf316b9f',
    messagingSenderId: '801641693646',
    projectId: 'doclink-d30a3',
    storageBucket: 'doclink-d30a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycLeC-azO-wGAGUP7nm299JcSz3RpeRk',
    appId: '1:801641693646:ios:dbf79566a285a943316b9f',
    messagingSenderId: '801641693646',
    projectId: 'doclink-d30a3',
    storageBucket: 'doclink-d30a3.appspot.com',
    androidClientId:
        '801641693646-uchd5oqontltk5b2ugg60mg3550aik2t.apps.googleusercontent.com',
    iosClientId:
        '801641693646-bf9mfdeec20j1j1rrbnnqkte98bca438.apps.googleusercontent.com',
    iosBundleId: 'com.Ahmed.myDoctoryApp.eg.doctory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycLeC-azO-wGAGUP7nm299JcSz3RpeRk',
    appId: '1:801641693646:ios:dbf79566a285a943316b9f',
    messagingSenderId: '801641693646',
    projectId: 'doclink-d30a3',
    storageBucket: 'doclink-d30a3.appspot.com',
    androidClientId:
        '801641693646-uchd5oqontltk5b2ugg60mg3550aik2t.apps.googleusercontent.com',
    iosClientId:
        '801641693646-bf9mfdeec20j1j1rrbnnqkte98bca438.apps.googleusercontent.com',
    iosBundleId: 'com.Ahmed.myDoctoryApp.eg.doctory',
  );
}
